name: hydration
channels:
  - conda-forge/label/openmm_dev
  - openeye
  - defaults
dependencies:
  - openmm=8
  - openmmtools
  - openmmforcefields
  - openeye-toolkits
  - click
  - rich
  - pyyaml
  # for analysis
  - pandas
  - scipy
  - seaborn
  - matplotlib
  # install espaloma_charge (until it appears on conda-forge)
  - pip
  - pip:
    - git+https://github.com/choderalab/espaloma_charge.git
